name: mmovies
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-292.0.dev <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_custom_dialog: ^1.3.0
  flutter_downloader: ^1.11.1
  flutter_file_downloader: ^1.1.2
  http: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  scroll_snap_list: ^0.9.1
  shared_preferences: ^2.2.0
  video_player: ^2.7.0
  web_socket_channel: ^2.4.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/movie.png
    - assets/person1.png
    - assets/world.png
    - assets/flag.jpg